# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Helderberg Devs
email:
description: Helderberg software developer community and monthly meetup for Somerset West, Strand, and Gordon's Bay.
minimal_mistakes_skin: mint
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: ZA # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Try override GitHub pages messing up HTTPS/HTTP
url: https://helderberg.dev
baseurl: /

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Helderberg Devs"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Join our monthly, in-person meetup and Slack channel for discussion"
  flag     : "/assets/images/south-africa-flag-32.png"
  location : "Helderberg, South Africa"
  links:
    - label: "Meetup Events"
      icon: "fas fa-fw fa-calendar-alt"
      url: "https://www.facebook.com/groups/helderberg.swdev.entrep.meetups"
    - label: "ZATech Slack"
      icon: "fab fa-fw fa-slack-hash"
      url: "https://zatech.slack.com/app_redirect?channel=helderberg-devs"

footer:
  links:

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

tag_archive:
  type: liquid
  path: /tags/

atom_feed:
  hide: true
